budget: 1000
budget_type: classifier
class_column: class
data_description: Example dataset description
dataset_id: null
gridding: 0
k_window: 5
methods: [rf, knn, svm, dt, pa, logreg, bnb, mlp, ada, mnb, gp, gnb, sgd, et]
metric: f1
priority: 1
r_minimum: 2
score_target: cv
selector: bestk
test_path: null
train_path: atm/data/test/pollution_1.csv
tuner: gp
